<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /xml/schema/CRM/HelloassoPaymentProcessor/HelloAssoMetadata.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:e3a11923365d6c95422197071a3e1d0a)
 */

/**
 * Database access object for the HelloAssoMetadata entity.
 */
class CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata extends CRM_Core_DAO {
  const EXT = 'civicrm';
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_hello_asso_metadata';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique HelloassoMetaData ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contribution
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contribution_id;

  /**
   * Key used to sign contribution
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $signing_key;

  /**
   * @var int|string
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $helloasso_ref_cmd_id;

  /**
   * @var int|string
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $checkout_intent_id;

  /**
   * @var int|string
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $helloasso_payment_id;

  /**
   * @var string
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_type;

  /**
   * @var string
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $state;

  /**
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $payment_processor_id;

  /**
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sync_origin_date;

  /**
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sync_next_date;

  /**
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sync_last_date;

  /**
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sync_attempt_count;

  /**
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sync_error_count;

  /**
   * @var string
   *   (SQL type: varchar(16))
   *   Note that values will be retrieved from the database as a string.
   */
  public $long_sync_scheme;

  /**
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $long_sync_origin_date;

  /**
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $long_sync_next_date;

  /**
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $long_sync_last_date;

  /**
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $long_sync_attempt_count;

  /**
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $long_sync_error_count;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_hello_asso_metadata';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? ts('Hello Asso Metadatas') : ts('Hello Asso Metadata');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID'),
          'description' => ts('Unique HelloassoMetaData ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.id',
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contribution_id' => [
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Contribution ID'),
          'description' => ts('FK to Contribution'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.contribution_id',
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'EntityRef',
            'label' => ts("Contribution"),
          ],
          'add' => NULL,
        ],
        'signing_key' => [
          'name' => 'signing_key',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Signing Key'),
          'description' => ts('Key used to sign contribution'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.signing_key',
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'helloasso_ref_cmd_id' => [
          'name' => 'helloasso_ref_cmd_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('HelloAsso Reference command ID '),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.helloasso_ref_cmd_id',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'checkout_intent_id' => [
          'name' => 'checkout_intent_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Checkout intent ID'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.checkout_intent_id',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'helloasso_payment_id' => [
          'name' => 'helloasso_payment_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('HelloAsso Payment ID'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.helloasso_payment_id',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'event_type' => [
          'name' => 'event_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Last event type'),
          'required' => FALSE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.event_type',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'state' => [
          'name' => 'state',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Last known state'),
          'required' => FALSE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.state',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'payment_processor_id' => [
          'name' => 'payment_processor_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Payment processor ID'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.payment_processor_id',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'sync_origin_date' => [
          'name' => 'sync_origin_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Sync origin date'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.sync_origin_date',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'sync_next_date' => [
          'name' => 'sync_next_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Next scheduled sync date'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.sync_next_date',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'sync_last_date' => [
          'name' => 'sync_last_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Last sync date'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.sync_last_date',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'sync_attempt_count' => [
          'name' => 'sync_attempt_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Sync attempt count'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.sync_attempt_count',
          'default' => '0',
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'sync_error_count' => [
          'name' => 'sync_error_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Sync technical error count'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.sync_error_count',
          'default' => '0',
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'long_sync_scheme' => [
          'name' => 'long_sync_scheme',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Long follow-up scheme'),
          'required' => FALSE,
          'maxlength' => 16,
          'size' => CRM_Utils_Type::TWELVE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.long_sync_scheme',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'long_sync_origin_date' => [
          'name' => 'long_sync_origin_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Long sync origin date'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.long_sync_origin_date',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'long_sync_next_date' => [
          'name' => 'long_sync_next_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Next scheduled long sync date'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.long_sync_next_date',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'long_sync_last_date' => [
          'name' => 'long_sync_last_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Last long sync date'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.long_sync_last_date',
          'default' => NULL,
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'add' => NULL,
        ],
        'long_sync_attempt_count' => [
          'name' => 'long_sync_attempt_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Long sync attempt count'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.long_sync_attempt_count',
          'default' => '0',
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'long_sync_error_count' => [
          'name' => 'long_sync_error_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Long sync technical error count'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_hello_asso_metadata.long_sync_error_count',
          'default' => '0',
          'table_name' => 'civicrm_hello_asso_metadata',
          'entity' => 'HelloAssoMetadata',
          'bao' => 'CRM_HelloassoPaymentProcessor_DAO_HelloAssoMetadata',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hello_asso_metadata', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hello_asso_metadata', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_contribution_id' => [
        'name' => 'index_contribution_id',
        'field' => [
          0 => 'contribution_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hello_asso_metadata::0::contribution_id',
      ],
      'index_checkout_intent_id' => [
        'name' => 'index_checkout_intent_id',
        'field' => [
          0 => 'checkout_intent_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hello_asso_metadata::0::checkout_intent_id',
      ],
      'index_helloasso_payment_id' => [
        'name' => 'index_helloasso_payment_id',
        'field' => [
          0 => 'helloasso_payment_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hello_asso_metadata::0::helloasso_payment_id',
      ],
      'index_payment_processor_id_sync_next_date' => [
        'name' => 'index_payment_processor_id_sync_next_date',
        'field' => [
          0 => 'payment_processor_id',
          1 => 'sync_next_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hello_asso_metadata::0::payment_processor_id::sync_next_date',
      ],
      'index_sync_next_date' => [
        'name' => 'index_sync_next_date',
        'field' => [
          0 => 'sync_next_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hello_asso_metadata::0::sync_next_date',
      ],
      'index_payment_processor_id_long_sync_next_date' => [
        'name' => 'index_payment_processor_id_long_sync_next_date',
        'field' => [
          0 => 'payment_processor_id',
          1 => 'long_sync_next_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hello_asso_metadata::0::payment_processor_id::long_sync_next_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
