<?php
/*
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC. All rights reserved.                        |
 |                                                                    |
 | This work is published under the GNU AGPLv3 license with some      |
 | permitted exceptions and without any warranty. For full license    |
 | and copyright information, see https://civicrm.org/licensing       |
 +--------------------------------------------------------------------+
 */

use CRM_HelloassoPaymentProcessor_ExtensionUtil as E;

return [
  'helloasso_v2_standard_frontend_bridge' => [
    'name' => 'helloasso_v2_standard_frontend_bridge',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Pont d'intégration standard (mjwshared)"),
    'description' => E::ts("Active l'intégration frontend standard HelloAsso basée sur CRM.payment et mjwshared."),
    'html_attributes' => [],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 10,
      ],
    ],
  ],
  'helloasso_v2_safe_abort_urls' => [
    'name' => 'helloasso_v2_safe_abort_urls',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Gestion sécurisée des URL d'échec et d'annulation"),
    'description' => E::ts("Évite de renvoyer les utilisateurs vers des URL CiviCRM ou AJAX fragiles lorsqu'un paiement est annulé ou échoue."),
    'html_attributes' => [],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 20,
      ],
    ],
  ],
  'helloasso_v2_queue_webhooks' => [
    'name' => 'helloasso_v2_queue_webhooks',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("File d'attente pour le traitement des webhooks"),
    'description' => E::ts('Place les webhooks HelloAsso dans la file PaymentprocessorWebhook au lieu de les traiter immédiatement.'),
    'html_attributes' => [],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 40,
      ],
    ],
  ],
  'helloasso_v2_followup_enabled' => [
    'name' => 'helloasso_v2_followup_enabled',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Fiabilisation du statut pour les automatisations (T+5 / T+15 min)"),
    'description' => E::ts("Active les contrôles automatiques à T+5 puis T+15 après création d'un checkout HelloAsso. Le suivi long des changements ultérieurs, notamment les remboursements, reste indépendant."),
    'html_attributes' => [],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 50,
      ],
    ],
  ],
  'helloasso_v2_afform_checkout' => [
    'name' => 'helloasso_v2_afform_checkout',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Intégration Afform / Form Builder"),
    'description' => E::ts("Publie une Checkout Option HelloAsso pour Afform / Form Builder en s'appuyant sur le mécanisme de checkout du core CiviCRM."),
    'html_attributes' => [],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 55,
      ],
    ],
  ],
  'helloasso_v2_cron_limit' => [
    'name' => 'helloasso_v2_cron_limit',
    'type' => 'Integer',
    'html_type' => 'text',
    'default' => 15,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Taille maximale des lots de traitement (Cron)"),
    'description' => E::ts('Nombre maximum de contributions HelloAsso traitées par processeur pendant une exécution normale du cron.'),
    'html_attributes' => ['size' => 6],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 60,
      ],
    ],
  ],
  'helloasso_v2_require_webhook_signature' => [
    'name' => 'helloasso_v2_require_webhook_signature',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => 0,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Vérification stricte de la signature historique"),
    'description' => E::ts('Refuse les webhooks HelloAsso dont la signature legacy invoiceID/sig est absente ou invalide.'),
    'html_attributes' => [],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 70,
      ],
    ],
  ],
  'helloasso_v2_require_partner_webhook_signature' => [
    'name' => 'helloasso_v2_require_partner_webhook_signature',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => 1,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Vérification stricte de la signature partenaire"),
    'description' => E::ts('Refuse les webhooks partenaire HelloAsso dont le header x-ha-signature est absent ou invalide quand une clé de signature webhook est enregistrée pour ce processeur.'),
    'html_attributes' => [],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 75,
      ],
    ],
  ],
  'helloasso_partner_auth_enabled' => [
    'name' => 'helloasso_partner_auth_enabled',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => 0,
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Mire HelloAsso : activer la connexion partagée'),
    'description' => E::ts("Active la mire OAuth HelloAsso partagée. Quand ce réglage est désactivé, l'interface mire n'est plus proposée sur les pages processeur HelloAsso."),
    'html_attributes' => [],
    'settings_pages' => [
      'helloasso' => [
        'weight' => 80,
      ],
    ],
  ],
  'helloasso_partner_client_id' => [
    'name' => 'helloasso_partner_client_id',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Mire HelloAsso : client ID partagé"),
    'description' => E::ts("Client ID fourni par HelloAsso pour la mire partagée. Ne pas versionner cette valeur dans un dépôt public."),
    'html_attributes' => ['size' => 48],
  ],
  'helloasso_partner_client_id_live' => [
    'name' => 'helloasso_partner_client_id_live',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Mire HelloAsso : client ID production'),
    'description' => E::ts('Client ID dédié à la mire HelloAsso production.'),
    'html_attributes' => ['size' => 48],
  ],
  'helloasso_partner_client_id_test' => [
    'name' => 'helloasso_partner_client_id_test',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Mire HelloAsso : client ID sandbox'),
    'description' => E::ts('Client ID dédié à la mire HelloAsso sandbox.'),
    'html_attributes' => ['size' => 48],
  ],
  'helloasso_partner_client_secret' => [
    'name' => 'helloasso_partner_client_secret',
    'type' => 'String',
    'html_type' => 'password',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Mire HelloAsso : client secret partagé"),
    'description' => E::ts("Client secret fourni par HelloAsso pour la mire partagée. À conserver localement sur l'instance CiviCRM."),
    'html_attributes' => ['size' => 48],
  ],
  'helloasso_partner_client_secret_live' => [
    'name' => 'helloasso_partner_client_secret_live',
    'type' => 'String',
    'html_type' => 'password',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Mire HelloAsso : client secret production'),
    'description' => E::ts('Client secret dédié à la mire HelloAsso production.'),
    'html_attributes' => ['size' => 48],
  ],
  'helloasso_partner_client_secret_test' => [
    'name' => 'helloasso_partner_client_secret_test',
    'type' => 'String',
    'html_type' => 'password',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Mire HelloAsso : client secret sandbox'),
    'description' => E::ts('Client secret dédié à la mire HelloAsso sandbox.'),
    'html_attributes' => ['size' => 48],
  ],
  'helloasso_partner_authorize_url' => [
    'name' => 'helloasso_partner_authorize_url',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'https://auth.helloasso.com/authorize',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts("Mire HelloAsso : URL d'autorisation"),
    'description' => E::ts("URL de l'écran d'autorisation HelloAsso. En production, la valeur par défaut est https://auth.helloasso.com/authorize."),
    'html_attributes' => ['size' => 64],
  ],
  'helloasso_partner_token_url' => [
    'name' => 'helloasso_partner_token_url',
    'type' => 'String',
    'html_type' => 'text',
    'default' => 'https://api.helloasso.com/oauth2/token',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Mire HelloAsso : URL du token'),
    'description' => E::ts("Endpoint HelloAsso utilisé pour échanger le code d'autorisation et rafraîchir les jetons OAuth."),
    'html_attributes' => ['size' => 64],
  ],
  'helloasso_partner_link_json' => [
    'name' => 'helloasso_partner_link_json',
    'type' => 'String',
    'html_type' => 'textarea',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('HelloAsso partner linked organization token'),
    'description' => E::ts('Internal storage for the linked organization OAuth token. Do not edit manually.'),
    'html_attributes' => [],
  ],
  'helloasso_processor_auth_json' => [
    'name' => 'helloasso_processor_auth_json',
    'type' => 'String',
    'html_type' => 'textarea',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('HelloAsso per-processor authorization state'),
    'description' => E::ts('Internal storage for sandbox authorization-screen state per HelloAsso payment processor. Do not edit manually.'),
    'html_attributes' => [],
  ],
];
