-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_hello_asso_metadata`;
DROP TABLE IF EXISTS `civicrm_hello_asso_installment`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_hello_asso_metadata
-- *
-- * HelloAsso payment reconciliation metadata
-- *
-- *******************************************************/
CREATE TABLE `civicrm_hello_asso_metadata` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique HelloassoMetaData ID',
  `contribution_id` int unsigned COMMENT 'FK to Contribution',
  `signing_key` text NOT NULL COMMENT 'Key used to sign contribution',
  `helloasso_ref_cmd_id` int NULL DEFAULT NULL,
  `checkout_intent_id` int NULL DEFAULT NULL,
  `helloasso_payment_id` int NULL DEFAULT NULL,
  `event_type` varchar(64) NULL DEFAULT NULL,
  `state` varchar(64) NULL DEFAULT NULL,
  `payment_processor_id` int unsigned NULL DEFAULT NULL,
  `sync_origin_date` datetime NULL DEFAULT NULL,
  `sync_next_date` datetime NULL DEFAULT NULL,
  `sync_last_date` datetime NULL DEFAULT NULL,
  `sync_attempt_count` int unsigned NULL DEFAULT 0,
  `sync_error_count` int unsigned NULL DEFAULT 0,
  `long_sync_scheme` varchar(16) NULL DEFAULT NULL,
  `long_sync_origin_date` datetime NULL DEFAULT NULL,
  `long_sync_next_date` datetime NULL DEFAULT NULL,
  `long_sync_last_date` datetime NULL DEFAULT NULL,
  `long_sync_attempt_count` int unsigned NULL DEFAULT 0,
  `long_sync_error_count` int unsigned NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `index_contribution_id` (`contribution_id`),
  INDEX `index_checkout_intent_id` (`checkout_intent_id`),
  INDEX `index_helloasso_payment_id` (`helloasso_payment_id`),
  INDEX `index_payment_processor_id_sync_next_date` (`payment_processor_id`, `sync_next_date`),
  INDEX `index_sync_next_date` (`sync_next_date`),
  INDEX `index_payment_processor_id_long_sync_next_date` (`payment_processor_id`, `long_sync_next_date`),
  CONSTRAINT FK_civicrm_hello_asso_metadata_contribution_id FOREIGN KEY (`contribution_id`) REFERENCES `civicrm_contribution`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_hello_asso_installment
-- *
-- * Idempotent mapping of HelloAsso installments to CiviCRM contributions
-- *
-- *******************************************************/
CREATE TABLE `civicrm_hello_asso_installment` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `payment_processor_id` int unsigned NOT NULL,
  `contribution_recur_id` int unsigned NOT NULL,
  `contribution_id` int unsigned NULL DEFAULT NULL,
  `checkout_intent_id` bigint unsigned NULL DEFAULT NULL,
  `order_id` bigint unsigned NOT NULL,
  `installment_number` int unsigned NOT NULL,
  `helloasso_payment_id` bigint unsigned NOT NULL,
  `amount` int unsigned NULL DEFAULT NULL,
  `payment_date` datetime NULL DEFAULT NULL,
  `state` varchar(64) NULL DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_processor_payment` (`payment_processor_id`, `helloasso_payment_id`),
  UNIQUE KEY `uniq_processor_order_installment` (`payment_processor_id`, `order_id`, `installment_number`),
  KEY `index_contribution_recur_id` (`contribution_recur_id`),
  KEY `index_contribution_id` (`contribution_id`),
  KEY `index_checkout_intent_id` (`checkout_intent_id`),
  CONSTRAINT `FK_hello_asso_installment_recur` FOREIGN KEY (`contribution_recur_id`) REFERENCES `civicrm_contribution_recur`(`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_hello_asso_installment_contribution` FOREIGN KEY (`contribution_id`) REFERENCES `civicrm_contribution`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_hello_asso_processor_auth
-- *
-- * HelloAsso per-processor OAuth and webhook state
-- *
-- *******************************************************/
CREATE TABLE `civicrm_hello_asso_processor_auth` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `payment_processor_id` int unsigned NOT NULL,
  `connection_mode` varchar(32) NULL DEFAULT NULL,
  `organization_slug` varchar(255) NULL DEFAULT NULL,
  `access_token` text NULL,
  `refresh_token` text NULL,
  `expires_at` int unsigned NULL DEFAULT NULL,
  `refresh_issued_at` int unsigned NULL DEFAULT NULL,
  `refresh_expires_at` int unsigned NULL DEFAULT NULL,
  `refresh_status` varchar(32) NULL DEFAULT NULL,
  `last_refresh_error` text NULL,
  `last_refresh_error_date` datetime NULL DEFAULT NULL,
  `last_refresh_http_status` int unsigned NULL DEFAULT NULL,
  `linked_at` datetime NULL DEFAULT NULL,
  `redirect_uri` text NULL,
  `webhook_ownership` varchar(32) NULL DEFAULT NULL,
  `webhook_url` text NULL,
  `webhook_signature_key` text NULL,
  `webhook_updated_at` datetime NULL DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_payment_processor_id` (`payment_processor_id`),
  KEY `index_connection_mode` (`connection_mode`),
  KEY `index_organization_slug` (`organization_slug`)
)
ENGINE=InnoDB;
